name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Environment Variable
      run: echo "wan_db=$WANDB_API_KEY"
      env:
        wan_db: ${{ secrets.WANDB_API_KEY }}

    - name: Run training script
      env:
        wan_db: ${{ secrets.WANDB_API_KEY }}
      run: python train.py
