wandb_version: 1

epochs:
  desc: null
  value: 15
batch_size:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716558619
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.11.7
      5: 0.17.0
      6: 4.41.0
      8:
      - 3
      - 5
      13: windows-amd64
